config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, as: :auth

  resources :collections, only: %i[show]
  resources :invoices
  root 'collections#index'

  namespace :admin_panel do
    resources :plates
    resources :collections
  end

  devise_for :admins, path: 'api/v1', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      registration: 'signup'
  }, controllers: {
      sessions: 'api/v1/admins/sessions',
      registrations: 'api/v1/admins/registrations'
  }
  
  namespace :api do
    namespace :v1 do
      resources :plates
      resources :collections
    end
  end
end

app/models/collection.rb
# frozen_string_literal: true

class Collection < ApplicationRecord
  has_many :plates, dependent: :destroy
  validates_presence_of :title

  has_many_attached :images

  def images_urls
    images.map { |image| Rails.application.routes.url_helpers.url_for(image) }.compact
  end
end

app/controllers/admin_panel/collections_controller.rb
# frozen_string_literal: true

module AdminPanel
  class CollectionsController < ApplicationController
    before_action :authenticate_auth_user!
    before_action :set_collection, only: %i[show edit update destroy]

    def index
      @collections = Collection.all
    end

    def show; end

    def new
      @collection = Collection.new
    end

    def create
      @collection = Collection.new(collection_params)
      if @collection.save
        redirect_to admin_panel_collection_path(@collection), notice: 'Collection was successfully created.'
      else
        render :new, alert: 'Error creating collection.'
      end
    end

    def edit; end

    def update
      if @collection.update(collection_params)
        redirect_to admin_panel_collection_path(@collection), notice: 'Collection was successfully updated.'
      else
        render :edit, alert: 'Error updating collection.'
      end
    end

    def destroy
      @collection.destroy
      redirect_to admin_panel_collections_path, notice: 'Collection was successfully destroyed.'
    end

    private

    def set_collection
      @collection = Collection.find(params[:id])
    end

    def collection_params
      params.require(:collection).permit(:title, :description, :publish, images: [])
    end
  end
end

app/controllers/api/v1/collections_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class CollectionsController < BaseController
      before_action :set_collection, only: %i[show update destroy]

      def index
        @collections = Collection.all
      end

      def show; end

      def create
        @collection = Collection.new(collection_params)
        if @collection.save
          render :show, status: :created, location: api_v1_collection_path(@collection)
        else
          render json: @collection.errors, status: :unprocessable_entity
        end
      end

      def update
        if @collection.update(collection_params)
          render :show
        else
          render json: @collection.errors, status: :unprocessable_entity
        end
      end

      def destroy
        @collection.destroy
        head :no_content
      end

      private

      def set_collection
        @collection = Collection.find(params[:id])
      end

      def collection_params
        params.require(:collection).permit(:title, :description, :publish, images: [])
      end
    end
  end
end

app/controllers/collections_controller.rb
# frozen_string_literal: true

class CollectionsController < ApplicationController
  before_action :set_collection, only: %i[show]

  def index
    generate_cache_key('collections')

    @collections = Collections::Index.call(@cache_key)
  end

  def show; end

  private

  def set_collection
    @collection = Collection.includes(:plates).find_by(id: params[:id])
  end

  def generate_cache_key(name)
    @cache_key = "#{name}_#{Collection.maximum(:updated_at)}"
  end
end

app/views/collections/index.html.erb
<div class="container mt-4">
  <h1 class="my-4">Collections</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @collections.each do |collection| %>
        <tr>
          <td><%= collection.title %></td>
          <td><%= truncate(collection.description, length: 100) %></td>
          <td>
            <%= link_to 'Show', collection_path(collection), class: 'btn btn-info btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/collections/show.html.erb
<div class="wrapper">
  <div class="collection__header">
    <div class="collection__header-big">
      <%= button_to root_path, method: :get, class: 'collection__header-text' do %>
        <%= image_tag 'Menu.svg', alt: 'Image' %>
        назад к коллекциям
      <% end %>
    </div>
    <div class="collection__header-small">
      <%= button_to root_path, method: :get, class: 'collection__header-text-small' do %>
        <%= image_tag 'Menu.svg', alt: 'Image' %>
      <% end %>
    </div>
    <div class="collection__header-logo">
      <%= image_tag 'Logo.svg', alt: 'Image', class:'collection__header--hexa' %>
    </div>
    <p class="collection__header-text">
      <span>tel-380977507277</span>
    </p>
    <p class="collection__header-text-small">
      <span>Inst fb</span>
    </p>
  </div>

  <div class="swiper">
  <div class="swiper-wrapper">
    <% if @collection.images.present? %>
      <% @collection.images.each do |image| %>
        <%= image_tag image, alt: 'logo', class:'swiper-slide' %>
      <% end %>
    <% end %>
  </div>

  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>
</div>

<div class="swiper-pagination"></div>


  <div class="collection__block-info">
    <div class="collection__block-info-column-first">
      <div class="collection__title">
        <%= @collection.title %>
      </div>

      <div class="collection__title-row">
        <div class="collection__title-small">
          <%= @collection.title %>
        </div>

        <%= image_tag 'logo_1.svg', alt: 'logo', class:'collection__logo-small-small' %>
      </div>

      <div class="collection__description">
        <%= @collection.description %>
      </div>

      <div class="collection__description">
        <%= image_tag 'video.svg', alt: 'video', class:'collection__video' %>
      </div>
    </div>

    <div class="collection__block-info-column-second">
      <%= image_tag 'logo_1.svg', alt: 'logo', class:'collection__logo-small' %>

      <div class="collection__grid">
        <% @collection.plates.each do |plate| %>
          <div class="collection__grid-element">
            <% if plate.image.present? %>
              <%= image_tag plate.image, alt: 'logo', class:'collection__grid-image' %>
            <% end %>
            <div class="collection__grid-element-text">
              <%= plate.title %>
            </div>
          </div>
        <% end %>
      </div>

      <%= link_to new_invoice_path(collection_id: @collection.id), class: 'collection__button' do %>
        <button class="collection__button">
          <div class="collection__button-text">
            узнать цену
          </div>
        </button>
      <% end %>
    </div>
  </div>
  <div class="collection__block-third">
    <div class="collection__block-third-column-first">
      <div class="collection__block-third-title">
        лучше увидеть в живую
      </div>
      <div class="collection__block-third-text">
        Мы создали для вас место, где представлены более 250 коллекций плитки, камня, сантехники и мебели от премиальных брендов. С целью комфорта за вами будет закреплён личный менеджер. По запросу также предоставляем услуги дизайнера. В шоу-руме функционирует зона отдыха. 
      </div>
    </div>

    <div class="collection__block-third-column-second">
      <button class="collection__button-block-third">
        <div class="collection__button-text-block-third">
          посетить шоу-рум
        </div>
      </button>
      <div class="collection__block-third-border-box">
        <div class="collection__block-third-text-border">
          Территория закрытого доступа, посещение по предварительной записи.
        </div>
      </div>
    </div>
  </div>

  <div class="collection__block-links">
    <div class="collection__block-links-text">
      Instagram
    </div>
    <div class="collection__block-links-text">
      facebook
    </div>
  </div>
</div>