config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, as: :auth

  resources :collections, only: %i[show]
  resources :invoices
  root 'collections#index'

  namespace :admin_panel do
    resources :plates
    resources :collections
  end

  devise_for :admins, path: 'api/v1', path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      registration: 'signup'
  }, controllers: {
      sessions: 'api/v1/admins/sessions',
      registrations: 'api/v1/admins/registrations'
  }
  
  namespace :api do
    namespace :v1 do
      resources :plates
      resources :collections
    end
  end
end

app/models/invoice.rb
# frozen_string_literal: true

class Invoice < ApplicationRecord
  validates_presence_of :name, :surname, :email
end

app/controllers/invoices_controller.rb
# frozen_string_literal: true

class InvoicesController < ApplicationController
  def new
    @invoice = Invoice.new
    @collection_id = params[:collection_id]
  end

  def create
    @invoice = Invoice.new(invoice_params)

    if @invoice.save
      puts @invoice.from
      InvoiceMailer.with(invoice: @invoice).invoice_created.deliver_now
      redirect_to new_invoice_path(collection_id: @invoice.from), notice: 'Invoice was successfully created and email was sent.'
    else
      render :new
    end
  end

  private

  def invoice_params
    params.require(:invoice).permit(:name, :surname, :email, :from)
  end
end

app/views/invoices/new.html.erb
<h1>Create a New Invoice</h1>

<%= form_with(model: @invoice, url: invoices_path, local: true, class: 'needs-validation', novalidate: true) do |form| %>
  <% if @invoice.errors.any? %>
    <div class="alert alert-danger">
      <h4 class="alert-heading">Please fix the following errors:</h4>
      <ul>
        <% @invoice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :surname, class: 'form-label' %>
    <%= form.text_area :surname, class: 'form-control', rows: 3, required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :email, class: 'form-label' %>
    <%= form.email_field :email, class: 'form-control', required: true %>
  </div>

  <%= form.hidden_field :from, value: @collection_id %>

  <div class="mb-3">
    <%= form.submit "Create Invoice", class: 'btn btn-primary' %>
  </div>
<% end %>

<div class="mt-3">
  <%= link_to 'Back', root_path, class: 'btn btn-secondary' %>
</div>